SCM_Frame/config/routes.rb
Rails.application.routes.draw do

  root to: "users#dashboard"
 
  get '/home' => 'users#home'

  post '/home' => 'users#signup'

  get '/dashboard' => 'users#dashboard'

  get '/board' => 'sessions#board'

  post '/board' => "sessions#create"

  delete '/logout' => "sessions#destroy"

  get '/reset' => 'users#reset'

  post '/reset' => "users#resetPassword"

  get '/import' => 'users#formImport'

  post '/import' => 'users#import'
  
  resources :users

end

SCM_Frame/app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  
  validates_presence_of :name

  validates_uniqueness_of :name, :case_sensitive => false

  validates :name, :length => { :in => 4..30}

  validates_presence_of :email

  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP } 

  validates_uniqueness_of :email, :case_sensitive => false

  validates_presence_of :password

  validates :password, :length => { :in => 6..30}
  
  validates :password, confirmation: true

  validates :password_confirmation, presence: true
  
  validates_presence_of :userProfile

  def self.to_csv(options = "")

  CSV.generate(options) do |csv|

    csv << column_names

    all.each do |user|

      csv << user.attributes.values_at(*column_names)

    end

  end

end

  before_create { generate_token(:remember_token)}

  def generate_token(column)

    begin 

      self[column] = SecureRandom.urlsafe_base64

    end while User.exists?(column => self[column])
    
  end
  
end

SCM_Frame/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def board

  end

  def create

    @user = UserService.findByEmail(email: params[:session][:email])

    if @user  && (@user.password == params[:session][:password])

      session[:user_id] = @user.id
      
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)

      flash.notice="Login successful" 

      redirect_to root_path 

    else

      flash.alert = "User not found"

      render 'board'

    end  
    
  end

  def destroy
  
    forget(current_user)

    session.delete(:user_id)

    @current_user = nil

    flash.notice="Logged out"
    
    redirect_to root_path

  end

end

SCM_Frame/app/controllers/users_controller.rb
class UsersController < ApplicationController

  require 'rubygems'

  require 'csv'

  def index

    if logged_in?

      @users = UserService.getAllUsers

      respond_to do |format|

        format.html

        format.csv { send_data @users.to_csv }

      end

    else

      flash.alert = "Please login"
    
      redirect_to '/board'
    
    end
    
  end

  def new

    if logged_in?

      @user = User.new

    else

      flash.alert = "Please login"

      redirect_to '/board'

    end

  end

  def create

    if logged_in?

      @user = User.new(user_params)

      @upload = params[:user][:userProfile]

      if (@upload)

        File.open( Rails.root.join('app/assets', 'images', @upload.original_filename), 'wb') do |file|
                  
        file.write( @upload.read )

        @user.userProfile =  @upload.original_filename
          
        end

      end

      @is_user_create = UserService.createUser(@user)

      respond_to do |format|

        @errorName = []

        @errorEmail = []

        @errorPsw = []

        @errorPswConfirm = []

        @errorPf = []

        if @is_user_create

          format.js

        else

        format.js

        @user.errors.any?

        if (@user.errors["name"] != nil)

          @errorName.push(@user.errors["name"][0])

        end

        if (@user.errors["email"] != nil)

          @errorEmail.push(@user.errors["email"][0])

        end

        if (@user.errors["password"] != nil)

          @errorPsw.push(@user.errors["password"][0])

        end
        
        if (@user.errors["password_confirmation"] != nil)

          @errorPswConfirm.push(@user.errors["password_confirmation"][0])
        end
          
        if (@user.errors["userProfile"] != nil)
          
          @errorPf.push(@user.errors["userProfile"][0])
        
        end

      end

    end

    else

      flash.alert = "Please login"

      redirect_to '/board'

    end

  end

  def show

    if logged_in?

      @user = UserService.getUserByID(params[:id])

    else

      flash.alert = "Please login"

      redirect_to '/board'
    
    end

  end
#
#  def edit
#
#    if logged_in?
#
#      @user = UserService.getUserByID(params[:id])
#  
#    else
#
#      redirect_to '/board'
#    
#    end
#
#  end
#
#  def update
#
#    if logged_in?
#
#      @user = UserService.getUserByID(params[:id])
#      
#      @is_user_update = UserService.updateUser(@user, update_params )
#
#      if @is_user_update
#
#        redirect_to users_path(@user)
#
#      else
#
#        flash.notice = "Something wrong"
#
#      end
#
#    else
#
#      redirect_to '/board'
#      
#    end
#
#  end

  def destroy

    if logged_in?

      @user = UserService.getUserByID(params[:id])

      UserService.destroyUser(@user)

      respond_to do |format|

        format.js
        
      end

    else

      flash.alert = "Please login"

      redirect_to '/board'
      
    end

  end
  

  def home

    @user = User.new

  end

  def signup

    @user = User.new(user_params)

    @upload = params[:user][:userProfile]

    if (@upload)

      File.open( Rails.root.join('app/assets', 'images', @upload.original_filename), 'wb') do |file|
                
      file.write( @upload.read )

      @user.userProfile =  @upload.original_filename
        
      end

    end

      @is_user_create = UserService.createUser(@user)

      if @is_user_create

        UserMailer.signup_confirmation(@user).deliver_now

        flash.notice="Sign up successful" 

        redirect_to root_path

      else

        render 'home'

      end

  end

  def dashboard

  end

  def reset

  end

  def resetPassword

    @user = UserService.findByEmail(email: params[:email])

    @new_password = params[:password]

    @new_password_confirm = params[:password_confirmation]

    if @user 

      if !@new_password.nil?  && !@new_password_confirm.nil? && @new_password == @new_password_confirm

        @user.password = @new_password
          
        @user.password_confirmation = @new_password_confirm
          
        @user.save
          
        flash.notice="Reset password successfully" 

        redirect_to root_path

      else

        flash.alert= "Please enter both new password and new password confirmation.(Both fields must match.)"

        render 'reset'

      end
      
    else

      flash.alert= "User not found"

      render 'reset'

    end

  end

  def formImport

  end

  def import

    begin

      @file = params[:importFile]

      CsvImportUsersService.new.call(@file)
    
      flash.notice = "Import Success"

      redirect_to users_url

    rescue Exception=>e

      flash.alert = "Something went wrong!!!"

      redirect_to users_url

    end

  end

  private 

  def user_params

   params.require(:user).permit(:name, :email, :password , :password_confirmation, :userProfile , :userType ,:phone, :address, :dob, :create_user_id, :updated_user_id, :deleted_user_id, :deleted_at)
  
  end

end

SCM_Frame/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>

  <title>SCMFrame</title>

  <meta name="viewport" content="width=device-width,initial-scale=1">

  <%= csrf_meta_tags %>

  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
    
  <%= stylesheet_link_tag    'style' %>
    
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  <%= javascript_include_tag "rails.validations",'data-turbolinks-track': 'reload' %>
 
  <%= javascript_importmap_tags %> 

</head>
   
<body>

  <%= render 'users/header' %>

  <% flash.each do |type, msg| %>

  <% if type= alert %>

    <div class="error-msg">

      <%= msg %>

    </div>

  <% else %>

    <div class="ok-msg">

      <%= msg %>
      
    </div>
    
  <% end %>

  <% end %><br>

  <%= yield %>

<script>

  $(document).ready( function () {

  $('#example').DataTable();

  } );

</script>
   
</body>

</html>

SCM_Frame/app/views/users/_form.html.erb
<%= form_with model: @user , local: false do |form| %>

  <div class="modal-body">

    <% if  @user.errors.full_messages.any? %>
      <% @user.errors.full_messages.each do |error_message| %>
        <div> <ul class="form-msg"><li><%= "*"+error_message + "." %></li></ul></div>
      <% end %>
    <% end %>

    <div class="form-group">
      <%= form.label :query, "Name"  %>
      <%= form.text_field :name , class:"form-control"  %>
      <span id = "nameBlock"></span>
    </div>

    <div class="form-group">
      <%= form.label :query, "E-Mail Address"    %>
      <%= form.email_field :email  , class:"form-control" %>
      <span id = "emailBlock"></span>
    </div>

    <div class="form-group">
      <%= form.label :query, "Password"  %>
      <%= form.password_field :password , class:"form-control" %>
      <span id = "pswBlock"></span>
    </div>

    <div class="form-group">
      <%= form.label :query, "Password Confirmation" %>
      <%= form.password_field :password_confirmation, class:"form-control" %>
      <span id = "pswConfirmBlock"></span>
    </div>

    <div class="form-group">
      <%= form.label :query, "Type"  %>
      <%= form.select :userType, [["Admin", "0"], ["User", "1"]] , {},  class:"form-control form-select-space" %>
    </div>

    <div class="form-group">
      <%= form.label :query, "Phone"  %>
      <%= form.text_field :phone , class:"form-control"  %>
    </div>

    <div class="form-group">
      <%= form.label :query, "Date of birth"  %>
      <%= form.date_field :dob , class:"form-control"  %>
    </div>

    <div class="form-group">
      <%= form.label :query, "Address"  %>
      <%= form.text_field :address , class:"form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :query, "Profile"  %>
      <%= form.file_field :userProfile , accept:'image/*' , class:"form-control-file"%>
      <span id = "pfBlock"></span>
    </div>

    <div class="form-group">
      <%= form.label :query, "Create User ID"  %>
      <% if current_user %>
        <%= form.text_field :create_user_id , value:current_user.id ,  class:"form-control"%>
      <% else %>
        <%= form.text_field :create_user_id  , class:"form-control" %>
      <% end %>
    </div>

  </div>

    <div class="modal-footer">
      <button type="button" class="btn btn-secondary no-modal" data-bs-dismiss="modal">Close</button>
      <%= form.submit "Create New User" , class: "btn btn-success"    %>
    </div>

<% end %>

SCM_Frame/app/views/users/_header.html.erb
<ul>

<li><%= link_to "Home", root_path, class: current_class?(root_path)  %></li>

<% if logged_in? %>

  <li><%= link_to "Users", users_path , class: current_class?(users_path) %></li>
    
  <li><%= link_to "logout", logout_path, method: :delete, class: current_class?(logout_path) %></li>
  
<% else %>
    
  <li><%= link_to "Signup", home_path , class: current_class?(home_path) %></li>
    
  <li><%= link_to "Login", board_path , class: current_class?(board_path) %></li>
 
<% end %>

</ul>

SCM_Frame/app/views/users/_show.html.erb
<div class="modal-body">

  <%= image_tag(user.userProfile, :alt => "rss feed" , class: 'profile-img' ) %>
        
  <p>Name: <%= user.name %></p>

  <p>Type:
    <% if user.userType == "0" %>
      <%= "Admin" %>
    <% else %>
      <%= "User" %>
    <% end %>
  </p>

  <p>Email: <%= user.email %></p>

  <p>Phone: <%= user.phone %></p>

  <p>Date of Birth: <%= user.dob.strftime("%Y/%m/%d") %></p>

  <p>Address: <%= user.address %></p>

  <p>Created Date<%= user.created_at.strftime("%Y/%m/%d") %></p>

  <p>Created User:
    <% if @user = User.find_by_id(user.create_user_id) %>
      <%= @user.name %>
    <% else %>
      <%= "-" %>
    <% end %>
  </p>

  <p>Updated Date:<%= user.updated_at.strftime("%Y/%m/%d") %></p>
  
  <p>Updated User:
    <% if @user = User.find_by_id(user.updated_user_id) %>
      <%= @user.name %>
    <% else %>
      <%= "-" %>
    <% end %>
  </p>

</div>

<div class="modal-footer">
  <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
</div>

SCM_Frame/app/views/users/_user_row.html.erb
<tr id="userRow<%= user.id %>">
						
	<td>		

		<%= link_to user.name, user , data:{bs_toggle: 'modal', bs_target: '#showUserModal', remote: true}%>			
	
	</td>

	<td><%= user.email %></td>

	<td>

	<% if @user = User.find_by_id(user.create_user_id) %>

		<%= @user.name %>

	<% else %>

		<%= "" %>

	<% end %>

	</td>

	<td>

	<% if user.userType == "0" %>

		<%= "Admin" %>

	<% else %>

		<%= "User" %>

	<% end %>

	</td>

	<td><%= user.phone %></td>

	<td><%= user.dob.strftime("%Y/%m/%d") %></td>

	<td><%= user.address %></td>

	<td><%= user.created_at.strftime("%Y/%m/%d") %></td>

	<td><%= user.updated_at.strftime("%Y/%m/%d") %></td>
						
	<td>

		<% if user == current_user %>

			<%= "" %>

		<% else %>
						
			<button class="btn btn-danger deletebtn" onclick="confirmDeleteModal(<%=  user.id %>)" >Delete</button>

			<!-- Delete Modal -->
			<div class="modal fade" id="exampleModal<%=user.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
				<div class="modal-dialog" role="document">
					<div class="modal-content">
						<div class="modal-header">
								<h5 class="modal-title" id="exampleModalLabel">Delete Confirm</h5>
								<button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
									<span aria-hidden="true">&times;</span>
								</button>
							</div>
							<div class="modal-body">
								<p> Are you sure to delete this user? </p>
								<p>ID: <%= user.id %></p>
								<p>Name: <%= user.name %></p>
								<p>Email: <%= user.email %></p>
								<p>Phone: <%= user.phone %></p>
								<p>Date of Birth: <%= user.dob.strftime("%Y/%m/%d") %></p>
								<p>Address: <%= user.address %></p>
							</div>
							<div class="modal-footer">
								<button type="button" class="btn btn-secondary no-modal" id="no" data-bs-dismiss="modal">Cancel</button>
								<%= link_to 'Delete', user_path(user), class:"btn btn-danger sure", method: 'delete' ,  remote: true , onclick:"stopModal(#{user.id})" %>
							</div>
						</div>
					</div>
				</div>

			<% end %>

		</td>	

</tr>	

SCM_Frame/app/views/users/create.js.erb
<% if @user.errors.any? %>

  $(".message").remove();

  $("#nameBlock").append('<div class="message"><%= escape_javascript(@errorName[0])%></div>');

  $("#emailBlock").append('<div class="message"><%= escape_javascript( @errorEmail[0])%></div>');

  $("#pswBlock").append('<div class="message"><%= escape_javascript( @errorPsw[0])%></div>');

  $("#pswConfirmBlock").append('<div class="message"><%= escape_javascript( @errorPswConfirm[0])%></div>');

  $("#pfBlock").append('<div class="message"><%= escape_javascript(@errorPf[0])%></div>');

<% else %>

  $('#tableBody').append("<%= escape_javascript render('user_row', user: @user) %>");

  $('.no-modal').click();

<% end %>

SCM_Frame/app/views/users/destroy.js.erb
$('#userRow<%= @user.id %>').remove();

SCM_Frame/app/views/users/edit.html.erb
#<h5 class="form-header">Profile Edit</h5>
#
#<div class="form">
#
#<%= form_with model: @user  do |form| %>
#
#  <%= form.label :query, "Name" , class: "space"  %><br>
#  <%= form.text_field :name , class: "control"  %><br>
#
#  <%= form.label :query, "E-Mail Address"  , class: "space"  %><br>
#  <%= form.email_field :email , class: "control" %><br>
#
#  <%= form.label :query, "Type" , class: "space" %><br>
#  <%= form.select :userType, [["Admin", "0"], ["User", "1"]] , class: "control" %><br>
#
#  <%= form.label :query, "Phone" , class:"space" %><br>
#  <%= form.text_field :phone , class: "control" %><br>
#
#  <%= form.label :query, "Date of birth" , class:"space" %><br>
#  <%= form.date_field :dob , class: "control" %><br>
#
#  <%= form.label :query, "Address" , class:"space" %><br>
#  <%= form.text_field :address , class: "control" %><br>
#
#
#  <%= form.label :query, "New Profile" , class: "space" %><br>
#  <%= form.file_field :profile , accept:'image/*' , class: "file-control" %><br><br>
#
#  <%= form.label :query, "Update User ID" , class: "space"  %><br>
#  <% if current_user %>
#    <%= form.text_field :updated_user_id, class: "control", value:current_user.id %><br><br>
#  <% else %>
#    <%= form.text_field :updated_user_id , class: "control" %><br><br>
#  <% end %>
#
#  <%= form.submit "Update"  , class: "space signup"   %>
#
#  <%= form.submit "Clear" ,  id: "removeData"  %>
#
#<% end %>
#
#</div>

SCM_Frame/app/views/users/formImport.html.erb
<h5 class="form-header">Upload File into sql database</h5>

<%= form_with url: "/import", class: 'form' , method: :post  do |form| %>

  <%= form.label :query, "File:" %><br>
  <%= form.file_field :importFile  %><br><br>

  <%= form.submit "Upload" , class: 'cmn-btn'  %>
  <%= link_to 'Back', users_path  , class: 'btn btn-default' , id: 'back-btn' %>
  
<% end %>

SCM_Frame/app/views/users/home.html.erb
<h5 class="form-header">Register</h5>

<% if @user.errors.full_messages.any? %>

  <% @user.errors.full_messages.each do |error_message| %>

    <div> <ul class="form-msg"><li><%= "*"+error_message + "." %></li></ul></div>
  
  <% end %>

<% end %>

<div class="form">

  <%= form_with url: home_path , model: @user , validate: true do |form| %>

    <%= form.label :query, "Name" , class: "space"  %><br>
    <%= form.text_field :name , class: "control", id: "name"  %><br>

    <%= form.label :query, "E-Mail Address"  , class: "space"  %><br>
    <%= form.email_field :email , class: "control" , id: "email" %><br>

    <%= form.label :query, "Password" , class: "space" %><br>
    <%= form.password_field :password , class: "control" , id: "password" %><br>

    <%= form.label :query, "Password Confirmation" , class: "space" %><br>
    <%= form.password_field :password_confirmation , class: "control" , id: "password" %><br>
    
    <%= form.label :query, "Type" , class: "space" %><br>
    <%= form.select :userType, [["Admin", "0"], ["User", "1"]] , class: "control"  %><br>

    <%= form.label :query, "Phone" , class:"space" %><br>
    <%= form.text_field :phone , class: "control" , id: "phone" %><br>

    <%= form.label :query, "Date of birth" , class:"space" %><br>
    <%= form.date_field :dob , class: "control" , id: "dob" %><br>

    <%= form.label :query, "Address" , class:"space" %><br>
    <%= form.text_field :address , class: "control", id: "address" %><br>

    <%= form.label :query, "Profile" , class: "space" %><br>
    <%= form.file_field :userProfile , accept:'image/*' , class: "file-control" , id: "profile" %><br>

    <%= form.submit "Register" ,  class: "space signup"  %>

    <%= form.submit "Clear" ,  id: "clear"  %>

  <% end %>

</div>

<script>

$("#clear").on("click", function() {

  $("#name").val("");

  $("#email").val("");

  $("#password").val("");

  $("#password-confirmation").val("");

  $("#phone").val("");

  $("#dob").val("");

  $("#address").val("");
  
  $("#profile").val("");

});

</script>

SCM_Frame/app/views/users/index.html.erb
<h5 class="form-header">User List</h5>

<div>

	<%= link_to "New user", new_user_path  , class: 'cmn-btn',
	id:'new-user', data:{bs_toggle: 'modal', bs_target: '#newUserModal', remote: true} %>

	<div  class="btn-sec">

		<%= button_to 'Upload', import_path, method: :get , class: 'cmn-btn' , id: 'upload' %>
		
		<%= link_to "Download", users_path(format: "csv") , class: 'cmn-btn' , id: 'download' %>

	</div>

</div>

<div class="container">

	<table id="example" class='table table-striped table-sm'>

		<thead>

			<th>Name</th>

			<th>Email</th>

			<th>Created User</th>

			<th>Type</th>

			<th>Phone</th>

			<th>Date of birth</th>

			<th>Address</th>

			<th>Created_date</th>

			<th>Updated_date</th>

			<th>Delete</th>

		</thead>

		<tbody id="tableBody">

			<% @users.each do |user| %>
				
				<%= render 'user_row' , user: user %>
					
			<% end %>

		</tbody>

	</table>

</div>

<!-- Create Modal -->
<div class="modal fade" id="newUserModal" tabindex="-1" role="dialog" aria-labelledby="newUserModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="newUserModalLabel">Create New User</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
			<div id="newUserForm">
			</div>
    </div>
  </div>
</div>

<!-- Show Modal -->
<div class="modal fade" id="showUserModal" tabindex="-1" role="dialog" aria-labelledby="showUserModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="showUserModalLabel">User Confirm</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
			<div id="showUserDetails">
			</div>
    </div>
  </div>
</div>

<script type="text/javascript">

	function confirmDeleteModal(id){

		$('#exampleModal'+id).modal('show');

	}    

	function stopModal(id){
		
		$('#exampleModal'+id).modal('hide');
		
	} 

</script>

SCM_Frame/app/views/users/new.html.erb
<%= render 'form' %>

SCM_Frame/app/views/users/new.js.erb
$("#newUserForm").html("<%= escape_javascript render('form', user: @user) %>")

SCM_Frame/app/views/users/reset.html.erb
<h5 class="form-header">Reset Your Password</h5>

<div class="form">

<%= form_with url: "/reset", method: 'post' , model: @user do |form| %>
 
  <%= form.label :query, "E-Mail Address:"  , class: "space"  %>
  <%= form.email_field :email , class: "control" %><br>

  <%= form.label :query, "Enter new password" , class: "space" %>
  <%= form.password_field :password , class: "control" %><br>

  <%= form.label :query, "Type new password again" , class: "space" %>
  <%= form.password_field :password_confirmation, class: "control" %><br>

  <%= form.submit "Reset Password" , id: "login-space", class: "reset" %>
  
  <%= link_to "Back", board_path %>

 <% end %>
 
</div>

SCM_Frame/app/views/users/show.js.erb
$('#showUserDetails').html("<%= escape_javascript render('show', user: @user) %>")