Tutorial8/config/routes.rb
Rails.application.routes.draw do
 
  root "access#home"

  get "home"    => "access#home"

  get "login"   => "access#new"

  get "logout"  => "access#destroy"

  resource :access, controller: 'access'

end

Tutorial8/app/controllers/access_controller.rb
class AccessController < ApplicationController
  
  def home

    @username = cookies[:username]

  end

  def new
  end

  def create

    cookies[:username] = { value: params[:username]  , expires: Time.now + 60.seconds }

    cookies[:email] = { value: params[:email]  , expires: Time.now + 60.seconds }
    
    redirect_to root_url

  end

  def destroy

    cookies.delete :username

    cookies.delete :email

    redirect_to root_url

  end

end

Tutorial8/app/helpers/access_helper.rb
module AccessHelper
end

Tutorial8/app/helpers/session_helper.rb
module SessionHelper
end

Tutorial8/app/views/access/home.html.erb
<h1 class="header">Welcome!!!</h1>

<% if @username %>
  Logged in as <%= @username %><br>
  <%= link_to '<button class="logout">Logout</button>'.html_safe, logout_path %>
<% else %>
  <%= link_to '<button class="login">Login</button>'.html_safe, login_path %>
<% end %>

Tutorial8/app/views/access/new.html.erb
<h1 class="header">Log In</h1>

<%= link_to '<button class="back">Back</button>'.html_safe, :back %>

<div id="form">
<%= form_tag access_path do %>
  <div>
    <%= label_tag :username %><br/> 
    <%= text_field_tag "username",nil , class: "control", required: true, pattern: '^([a-zA-Z])+([\w]{2,})+$', placeholder: 'Enter username(at least 3 characters, no space allowed)' %>
  </div>
  <div>
  <%= label_tag :email %><br/>
  <%= email_field_tag :email,  params[:email] , class: 'control', :required => true, :pattern => '[^@]+@[^@]+\.[a-zA-Z]{2,6}' , placeholder: "Please enter valid email" %>
  </div>
  <button class="login form-login">Log in</button>
<% end %>
</div>

Tutorial8/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tutorial8</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'style.css' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>